version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'myappdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8087:80
    environment:
      - PMA_ARBITRARY=1
  app:
    container_name: app
    image: appflask:1.0.1
    restart: always
    ports:
      - 5050:5050
    environment:
      - MYSQL_HOST=10.1.1.1
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=myappdb

volumes:
  db-data:
