apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: myapp
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: dmenacho8/appflask:1.0.0
        name: myapp
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: mysql_password
        - name: MYSQL_DB
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mysql_db
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mysql_host
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mysql_user
