apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pma
  name: pma
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pma
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pma
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin:latest
        name: pma
        env:
        - name: PMA_ARBITRARY
          value: "1"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pma
  labels:
    app: pma
spec:
  type: NodePort
  selector:
    app: pma
  ports:
  - port: 8080
    nodePort: 30087
    targetPort: 80
